[unstable]
codegen-backend = true

[build]
jobs = 16

[target.x86_64-unknown-linux-gnu]
rustflags = [
    "-C", "link-arg=-fuse-ld=mold",
]

[target.aarch64-linux-android]
linker = "/opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android33-clang"
rustflags = ["-C", "target-feature=+neon"]

[target.wasm32-wasip1]
rustflags = ["-C", "target-feature=+atomics,+bulk-memory"]

[target.wasm32-unknown-unknown]
rustflags = ["-C", "opt-level=z", "--cfg", "web_sys_unstable_apis"]

[target.x86_64-pc-windows-msvc]
linker = "lld"
rustflags = [
    "-Lnative=/home/stream/.xwin/crt/lib/x86_64",
    "-Lnative=/home/stream/.xwin/sdk/lib/um/x86_64",
    "-Lnative=/home/stream/.xwin/sdk/lib/ucrt/x86_64",
]

[profile.dev]
incremental = true
codegen-backend = "cranelift"
debug = 1
split-debuginfo = "unpacked"
strip = "debuginfo"
lto = false

[profile.release]
incremental = true
opt-level = 3
codegen-units = 1
lto = "fat"
panic = "abort"
overflow-checks = false
debug-assertions = false
strip = true
rustflags = ["-C", "target-cpu=x86-64-v3"]
