[unstable]
codegen-backend = true

[target.x86_64-unknown-linux-gnu]
rustflags = [
    "-C", "link-arg=-fuse-ld=mold",
    "-C", "target-feature=+avx,+fma,+sse"
]

[target.aarch64-linux-android]
linker = "/opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android33-clang"
rustflags = ["-C", "target-feature=+neon"]

[target.wasm32-wasip1]
rustflags = ["-C", "target-feature=+atomics,+bulk-memory"]

[target.wasm32-unknown-unknown]
rustflags = ["-C", "opt-level=z", "--cfg", "web_sys_unstable_apis"]

[target.x86_64-pc-windows-msvc]
ar = "llvm-lib"
linker = "lld-link"
rustflags = [
    "-Lnative=/home/stream/.xwin/crt/lib/x86_64",
    "-Lnative=/home/stream/.xwin/sdk/lib/um/x86_64",
    "-Lnative=/home/stream/.xwin/sdk/lib/ucrt/x86_64",
]

[profile.dev]
incremental = true
codegen-backend = "cranelift"
lto = false

[profile.release]
incremental = false
opt-level = 3
lto = "thin"
panic = "abort"
overflow-checks = false
debug-assertions = false
strip = true

[env]
CC_aarch64_linux_android = "/opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android33-clang"
CXX_aarch64_linux_android = "/opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android33-clang++"
AR_aarch64_linux_android = "/opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar"
CC_x86_64_pc_windows_msvc = "clang-cl"
CXX_x86_64_pc_windows_msvc = "clang-cl"
AR_x86_64_pc_windows_msvc = "llvm-lib"
XWIN_DIR="/home/stream/.xwin"
